
<!DOCTYPE html>
<html lang="en">
<head>

    <title>rSlider.js: Range Slider Demos</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/rSlider.min.css" rel="stylesheet">
    <link href="css/dselect.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
</head>
<body>
<select class="form-select" id="example">
    <option value="1">JavaScript</option>
    <option value="2">HTML5</option>
    <option value="3">CSS3</option>
    <option value="4">Bootstrap</option>
    <option value="5">Tailwind</option>
</select>


<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap.bundle.min.js"></script>
<script src="js/jquery-3.6.4.min.js"></script>
<script src="js/dselect.js"></script>
<script src="js/rSlider.min.js"></script>
<script src="js/javaScript.js"></script>
</body>
</html>